<?php
return array(
	'BE' => array(
		'allowDonateWindow' => '0',
		'elementVersioningOnly' => '1',
		'explicitADmode' => 'explicitAllow',
		'fileCreateMask' => '0664',
		'flexformForceCDATA' => '1',
		'folderCreateMask' => '02775',
		'installToolPassword' => 'f0263f26a9409df1a61156366543bce6',
		'loginSecurityLevel' => 'rsa',
		'maxFileSize' => 25600,
		'pageTree' => array(
			'preloadLimit' => '500',
		),
		'sessionTimeout' => '60000',
		'unzip_path' => 'unzip',
		'versionNumberInFilename' => '1',
	),
	'DB' => array(
		'database' => 't3orgdev',
		'host' => '127.0.0.1',
		'password' => 'root',
		'port' => 3306,
		'username' => 'root',
	),
	'EXT' => array(
		'allowLocalInstall' => '1',
		'extCache' => '1',
		'extConf' => array(
			'amqp' => 'a:5:{s:8:"username";s:5:"admin";s:8:"password";s:5:"typo3";s:4:"host";s:9:"t3org.dev";s:4:"port";s:4:"5672";s:5:"vhost";s:7:"vagrant";}',
			'be_groups' => 'a:1:{s:13:"explicitAllow";s:1:"0";}',
			'crawler' => 'a:14:{s:9:"sleepTime";s:4:"1000";s:16:"sleepAfterFinish";s:2:"10";s:11:"countInARun";s:2:"50";s:14:"purgeQueueDays";s:2:"14";s:12:"processLimit";s:1:"4";s:17:"processMaxRunTime";s:3:"300";s:12:"processDebug";s:1:"0";s:16:"crawlHiddenPages";s:1:"1";s:7:"phpPath";s:13:"/usr/bin/php5";s:14:"enableTimeslot";s:1:"1";s:11:"logFileName";s:0:"";s:9:"follow30x";s:1:"0";s:18:"makeDirectRequests";s:1:"1";s:14:"maxCompileUrls";s:5:"10000";}',
			'css_filelinks' => 'a:4:{s:16:"dont_default_css";s:1:"0";s:20:"allow_read_from_path";s:1:"0";s:11:"default_dam";s:1:"1";s:11:"pathtoicons";s:0:"";}',
			'cz_simple_cal' => 'a:1:{s:13:"recurrenceEnd";s:10:"2020-12-31";}',
			'dam' => 'a:6:{s:8:"tsconfig";s:7:"default";s:13:"file_filelist";s:1:"0";s:15:"hideMediaFolder";s:1:"0";s:8:"mediatag";s:1:"1";s:15:"htmlAreaBrowser";s:1:"1";s:5:"devel";s:1:"0";}',
			'dam_filelinks' => 'a:7:{s:26:"ctype_media_add_orig_field";s:1:"0";s:15:"readFromPathDam";s:1:"0";s:11:"minElements";s:1:"0";s:11:"maxElements";s:2:"20";s:10:"allowedExt";s:0:"";s:22:"allowedExtReadFromPath";s:0:"";s:9:"dam_1_0_9";s:1:"1";}',
			'dam_ttcontent' => 'a:4:{s:28:"ctypes_textpic_image_add_ref";s:1:"1";s:35:"ctypes_textpic_image_add_orig_field";s:1:"1";s:19:"add_css_styled_hook";s:1:"1";s:17:"add_ws_mod_xclass";s:1:"1";}',
			'dam_ttnews' => 'a:2:{s:13:"media_add_ref";s:1:"1";s:20:"media_add_orig_field";s:1:"0";}',
			'devlog' => 'a:11:{s:10:"maxLogRuns";s:2:"15";s:14:"entriesPerPage";s:2:"25";s:7:"maxRows";s:4:"1000";s:8:"optimize";s:1:"0";s:8:"dumpSize";s:7:"1000000";s:11:"minLogLevel";s:2:"-1";s:11:"excludeKeys";s:0:"";s:14:"highlightStyle";s:60:"padding: 2px; background-color: #fc3; border: 1px solid #666";s:16:"refreshFrequency";s:1:"2";s:13:"prototypePath";s:0:"";s:11:"autoCleanup";s:1:"0";}',
			'docondemand' => 'a:3:{s:13:"repositoryDir";s:44:"/var/www/vhosts/t3org.dev/www/fileadmin/ter/";s:12:"unzipCommand";s:46:"unzip -qq ###ARCHIVENAME### -d ###DIRECTORY###";s:11:"logFullPath";s:0:"";}',
			'filemetadata' => 'a:0:{}',
			'js_css_optimizer' => 'a:17:{s:10:"bundle_css";s:1:"1";s:9:"bundle_js";s:1:"1";s:13:"remove_bslash";s:1:"0";s:15:"compress_colors";s:1:"0";s:20:"compress_font-weight";s:1:"0";s:11:"lowercase_s";s:1:"0";s:19:"optimise_shorthands";s:1:"0";s:11:"remove_last";s:1:"0";s:15:"case_properties";s:1:"0";s:15:"sort_properties";s:1:"0";s:14:"sort_selectors";s:1:"0";s:15:"merge_selectors";s:1:"0";s:26:"discard_invalid_properties";s:1:"0";s:9:"css_level";s:6:"CSS2.1";s:12:"preserve_css";s:1:"1";s:9:"timestamp";s:1:"0";s:10:"charsetCSS";s:0:"";}',
			'linkhandler' => 'a:2:{s:32:"applyXclassHideSaveAndViewButton";s:1:"0";s:32:"applyXclassToEnableSoftrefParser";s:1:"0";}',
			'linkvalidator' => 'a:0:{}',
			'pdf_generator2' => 'a:3:{s:17:"simulateStaticPdf";s:1:"0";s:17:"disableGzipForPdf";s:1:"1";s:7:"typeNum";s:3:"123";}',
			'phpmyadmin' => 'a:2:{s:12:"hideOtherDBs";s:1:"1";s:9:"uploadDir";s:21:"uploads/tx_phpmyadmin";}',
			'phpunit' => 'a:5:{s:18:"outoflinetestspath";s:0:"";s:17:"excludeextensions";s:51:"phpunit, templavoila, dam, aoe_realurlpath, crawler";s:7:"usepear";s:1:"0";s:10:"phpunitlib";s:0:"";s:33:"alwaysSimulateFrontendEnvironment";s:1:"1";}',
			'powermail' => 'a:8:{s:10:"usePreview";s:1:"1";s:12:"cssSelection";s:1:"1";s:14:"feusersPrefill";s:70:"name, address, telephone, fax, email, zip, city, country, www, company";s:12:"disableIPlog";s:1:"0";s:20:"disableBackendModule";s:1:"0";s:16:"disableStartStop";s:1:"0";s:7:"useIRRE";s:1:"1";s:12:"fileToolPath";s:9:"/usr/bin/";}',
			'purge' => 'a:5:{s:15:"overrideDomains";s:9:"localhost";s:11:"expainsPids";s:0:"";s:16:"enablePurgeCalls";s:1:"1";s:27:"disableL10nmgrPurgeRequests";s:1:"0";s:28:"enableAsynchronousProcessing";s:1:"0";}',
			'realurl' => 'a:5:{s:10:"configFile";s:25:"typo3conf/realurlconf.php";s:14:"enableAutoConf";s:1:"0";s:14:"autoConfFormat";s:1:"0";s:12:"enableDevLog";s:1:"0";s:19:"enableChashUrlDebug";s:1:"0";}',
			'rsaauth' => 'a:1:{s:18:"temporaryDirectory";s:41:"/var/www/vhosts/t3org.dev/www/rsaAuthTmp/";}',
			'rtehtmlarea' => 'a:13:{s:21:"noSpellCheckLanguages";s:23:"ja,km,ko,lo,th,zh,b5,gb";s:15:"AspellDirectory";s:15:"/usr/bin/aspell";s:17:"defaultDictionary";s:2:"en";s:14:"dictionaryList";s:2:"en";s:20:"defaultConfiguration";s:105:"Typical (Most commonly used features are enabled. Select this option if you are unsure which one to use.)";s:12:"enableImages";s:1:"1";s:20:"enableInlineElements";s:1:"0";s:19:"allowStyleAttribute";s:1:"1";s:24:"enableAccessibilityIcons";s:1:"0";s:16:"enableDAMBrowser";s:1:"0";s:16:"forceCommandMode";s:1:"0";s:15:"enableDebugMode";s:1:"0";s:23:"enableCompressedScripts";s:1:"1";}',
			'saltedpasswords' => 'a:2:{s:3:"FE.";a:5:{s:7:"enabled";s:1:"1";s:21:"saltedPWHashingMethod";s:31:"tx_saltedpasswords_salts_phpass";s:11:"forceSalted";s:1:"1";s:15:"onlyAuthService";s:1:"0";s:12:"updatePasswd";s:1:"0";}s:3:"BE.";a:4:{s:21:"saltedPWHashingMethod";s:31:"tx_saltedpasswords_salts_phpass";s:11:"forceSalted";s:1:"1";s:15:"onlyAuthService";s:1:"0";s:12:"updatePasswd";s:1:"0";}}',
			'scheduler' => 'a:3:{s:11:"maxLifetime";s:4:"1440";s:11:"enableBELog";s:1:"0";s:13:"showTestTasks";s:1:"0";}',
			'static_info_tables' => 'a:2:{s:7:"charset";s:5:"utf-8";s:12:"usePatch1822";s:1:"0";}',
			't3skin' => 'a:0:{}',
			'templavoila' => 'a:2:{s:7:"enable.";a:2:{s:13:"oldPageModule";s:1:"0";s:16:"selectDataSource";s:1:"0";}s:9:"staticDS.";a:3:{s:6:"enable";s:1:"1";s:8:"path_fce";s:31:"EXT:t3org_base/templavoila/fce/";s:9:"path_page";s:32:"EXT:t3org_base/templavoila/page/";}}',
			'ter' => 'a:1:{s:13:"repositoryDir";s:44:"/var/www/vhosts/t3org.dev/www/fileadmin/ter/";}',
			'ter_doc' => 'a:6:{s:13:"repositoryDir";s:44:"/var/www/vhosts/t3org.dev/www/fileadmin/ter/";s:12:"unzipCommand";s:46:"unzip -qq ###ARCHIVENAME### -d ###DIRECTORY###";s:10:"cliVerbose";s:1:"0";s:11:"logFullPath";s:0:"";s:14:"typoscriptFile";s:46:"EXT:ter_doc/Configuration/TypoScript/static.ts";s:10:"storagePid";s:3:"417";}',
			'ter_fe' => 'a:3:{s:7:"WSDLURI";s:37:"http://t3org.dev/wsdl/tx_ter_wsdl.php";s:14:"SOAPServiceURI";s:33:"http://t3org.dev/index.php?id=ter";s:13:"repositoryDir";s:44:"/var/www/vhosts/t3org.dev/www/fileadmin/ter/";}',
			'tika' => 'a:7:{s:9:"extractor";s:4:"solr";s:8:"tikaPath";s:0:"";s:8:"solrHost";s:14:"192.168.20.110";s:8:"solrPort";s:4:"8080";s:8:"solrPath";s:9:"/solr/t3o";s:10:"solrScheme";s:4:"http";s:11:"solrUseCurl";s:1:"0";}',
			'tt_news' => 'a:20:{s:13:"useStoragePid";s:1:"1";s:17:"requireCategories";s:1:"0";s:18:"useInternalCaching";s:1:"1";s:11:"cachingMode";s:6:"normal";s:13:"cacheLifetime";s:1:"0";s:13:"cachingEngine";s:16:"cachingFramework";s:11:"treeOrderBy";s:5:"title";s:13:"prependAtCopy";s:1:"1";s:5:"label";s:5:"title";s:9:"label_alt";s:5:"short";s:10:"label_alt2";s:5:"short";s:15:"label_alt_force";s:1:"0";s:21:"categorySelectedWidth";s:1:"0";s:17:"categoryTreeWidth";s:1:"0";s:25:"l10n_mode_prefixLangTitle";s:1:"1";s:22:"l10n_mode_imageExclude";s:1:"1";s:20:"hideNewLocalizations";s:1:"0";s:24:"writeCachingInfoToDevlog";s:10:"disabled|0";s:23:"writeParseTimesToDevlog";s:1:"0";s:18:"parsetimeThreshold";s:3:"0.1";}',
			'typo3_agencies' => 'a:2:{s:10:"storagePid";s:3:"329";s:14:"clearCachePids";s:7:"128,435";}',
			'vimeo_connector' => 'a:5:{s:3:"api";s:28:"http://vimeo.com/api/rest/v2";s:11:"consumerKey";s:32:"83dc97295d5e0a7bac63e23c4383650f";s:14:"consumerSecret";s:16:"e2a9e63f5dd2d6b6";s:11:"userAccount";s:11:"typo3videos";s:10:"storagePid";s:3:"447";}',
			'wt_spamshield' => 'a:10:{s:12:"useNameCheck";s:1:"1";s:12:"usehttpCheck";s:1:"3";s:9:"notUnique";s:0:"";s:13:"honeypotCheck";s:1:"1";s:15:"useSessionCheck";s:1:"1";s:16:"SessionStartTime";s:2:"10";s:14:"SessionEndTime";s:4:"1800";s:10:"AkismetKey";s:0:"";s:12:"email_notify";s:0:"";s:3:"pid";s:2:"-1";}',
		),
	),
	'EXTCONF' => array(
		'ajaxlogin' => array(
			'pageNotFound_handling' => '/index.php?id=15',
			'unauthorized_handling' => 'REDIRECT:/my-account/login/',
			'unauthorized_handling_statheader' => 'HTTP/1.1 401 Unauthorized',
		),
	),
	'FE' => array(
		'addRootLineFields' => ',subtitle,author,keywords,description,tx_realurl_pathsegment,tx_realurl_exclude,tx_templavoila_ds,tx_templavoila_to,tx_templavoila_next_ds,tx_templavoila_next_to',
		'cHashExcludedParametersIfEmpty' => '*',
		'debug' => '1',
		'disableNoCacheParameter' => '1',
		'hidePagesIfNotTranslatedByDefault' => '1',
		'lifetime' => '604800',
		'loginSecurityLevel' => 'rsa',
		'pageNotFound_handling' => 'USER_FUNCTION:tx_ajaxlogin_pagenotfoundhandler->handleError',
		'pageNotFound_handling_statheader' => 'HTTP/1.1 404 Not Found',
		'pageUnavailable_handling' => '/error_503.html',
		'versionNumberInFilename' => 'embed',
	),
	'GFX' => array(
		'TTFdpi' => '96',
		'im_path' => '/usr/bin/',
		'im_v5effects' => -1,
		'im_version_5' => 'gm',
		'jpg_quality' => '92',
		'png_truecolor' => '1',
	),
	'MAIL' => array(
		'defaultMailFromAddress' => '',
		'defaultMailFromName' => '',
		'transport' => 'smtp',
		'transport_mbox_file' => '',
		'transport_sendmail_command' => '/usr/sbin/sendmail -bs',
		'transport_smtp_encrypt' => '',
		'transport_smtp_password' => '',
		'transport_smtp_server' => 'localhost:1025',
		'transport_smtp_username' => '',
	),
	'SYS' => array(
		'UTF8filesystem' => '1',
		'belogErrorReporting' => 30709,
		'binSetup' => 'java = /usr/bin/java',
		'compat_version' => '6.2',
		'curlUse' => '1',
		'devIPmask' => '192.168.*',
		'displayErrors' => '1',
		'enableDeprecationLog' => '1',
		'encryptionKey' => '2603cd41e53a29d7111386d12df8d87ce95851d8ea1de42060fe872f6c23c0f2d896f695c8b5a83746830fcc2ccd7a1e',
		'maxFileNameLength' => '120',
		'no_pconnect' => '1',
		'recursiveDomainSearch' => '1',
		'sitename' => 'TYPO3.org - VagrantBox',
		'sqlDebug' => '1',
		'syslogErrorReporting' => 30709,
		'systemLog' => '',
		't3lib_cs_convMethod' => 'iconv',
		't3lib_cs_utils' => 'iconv',
		'trustedHostsPattern' => '[a-z0-9\\-_\\.]*t3org\\.dev',
		'useCachingFramework' => FALSE,
	),
);
?>