UPDATE tx_typo3agencies_domain_model_reference SET  industry=9, revenue=4 WHERE uid=1;
UPDATE tx_typo3agencies_domain_model_reference SET  industry=9, revenue=5 WHERE uid=3;
UPDATE tx_typo3agencies_domain_model_reference SET  industry=9, revenue=4 WHERE uid=6;
UPDATE tx_typo3agencies_domain_model_reference SET  industry=7, revenue=2 WHERE uid=7;
UPDATE tx_typo3agencies_domain_model_reference SET  industry=8, revenue=2 WHERE uid=9;
UPDATE tx_typo3agencies_domain_model_reference SET  industry=3, revenue=2 WHERE uid=10;
UPDATE tx_typo3agencies_domain_model_reference SET  industry=8, revenue=2 WHERE uid=11;
UPDATE tx_typo3agencies_domain_model_reference SET  industry=9, revenue=5 WHERE uid=12;
UPDATE tx_typo3agencies_domain_model_reference SET  industry=12, revenue = 6 WHERE uid=13;
UPDATE tx_typo3agencies_domain_model_reference SET  industry=12, revenue = 6 WHERE uid=14;
UPDATE tx_typo3agencies_domain_model_reference SET  industry=1, revenue = 5 WHERE uid=15;
UPDATE tx_typo3agencies_domain_model_reference SET  industry=3, revenue = 2 WHERE uid=16;
UPDATE tx_typo3agencies_domain_model_reference SET  industry=3, revenue = 2 WHERE uid=17;
UPDATE tx_typo3agencies_domain_model_reference SET  industry=2, revenue = 2 WHERE uid=18;
UPDATE tx_typo3agencies_domain_model_reference SET  industry=9, revenue = 5 WHERE uid=19;
UPDATE tx_typo3agencies_domain_model_reference SET  industry=8, revenue = 2 WHERE uid=20;
UPDATE tx_typo3agencies_domain_model_reference SET  revenue = 2 WHERE uid=21;
UPDATE tx_typo3agencies_domain_model_reference SET  revenue = 2 WHERE uid=22;
UPDATE tx_typo3agencies_domain_model_reference SET  revenue = 5 WHERE uid=23;
UPDATE tx_typo3agencies_domain_model_reference SET  revenue = 2 WHERE uid=24;
UPDATE tx_typo3agencies_domain_model_reference SET  revenue = 2 WHERE uid=25;
UPDATE tx_typo3agencies_domain_model_reference SET  revenue = 2 WHERE uid=26;
UPDATE tx_typo3agencies_domain_model_reference SET  revenue = 2 WHERE uid=27;
UPDATE tx_typo3agencies_domain_model_reference SET  revenue = 2 WHERE uid=28;
UPDATE tx_typo3agencies_domain_model_reference SET  revenue = 2 WHERE uid=29;
UPDATE tx_typo3agencies_domain_model_reference SET  revenue = 2 WHERE uid=30;
UPDATE tx_typo3agencies_domain_model_reference SET  revenue = 2 WHERE uid=31;